---
- name: Setup Wordpress 
  hosts: all
  become: yes
  tasks:
  - import_tasks: common/update-ubuntu.yaml
  - import_tasks: nunit/install-nunit.yaml
  - import_tasks: common/install-docker.yaml
  - import_tasks: common/install-mariadb.yaml
  - import_tasks: nunit/install-wordpress.yaml
  - import_tasks: nunit/setup-nunit.yaml

