---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Locust https to wordpress
      shell: |
        docker run -d -v "/root/f5j-nginx-performance-lab/docker-compose/locust:/mnt/locust" locustio/locust --config /mnt/locust/config/https_10-1-1-4_wp_s.conf -f /mnt/locust/senario/wp_top.py --html /mnt/locust/result/`date "+%Y-%m-%d-%H%M%S"`_https_10-1-1-4_wp_result.html 
        docker run -d -v "/root/f5j-nginx-performance-lab/docker-compose/locust:/mnt/locust" locustio/locust --config /mnt/locust/config/https_10-1-1-5_wp_s.conf -f /mnt/locust/senario/wp_top.py --html /mnt/locust/result/`date "+%Y-%m-%d-%H%M%S"`_https_10-1-1-5_wp_result.html 
        docker run -d -v "/root/f5j-nginx-performance-lab/docker-compose/locust:/mnt/locust" locustio/locust --config /mnt/locust/config/https_10-1-1-6_wp_s.conf -f /mnt/locust/senario/wp_top.py --html /mnt/locust/result/`date "+%Y-%m-%d-%H%M%S"`_https_10-1-1-6_wp_result.html 
