---
- name: Install apache2
  apt:
    name: apache2
    force_apt_get: yes
    update_cache: yes
    state: present

- name: Start service apache2, if not started
  service:
    name: apache2
    state: started

