{
 "title": "NGINX Unit / NGINX / Apache Dashboard",
 "description": "Host1: NGINX Unit / NGINX / Apache Dashboard",
 "tags": [ "linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "node1",
    "label": "Host1:",
    "query": {
     "query": "label_values(node_uname_info{}, instance)"
    }
   },
   {
    "name": "node2",
    "label": "Host2:",
    "query": {
     "query": "label_values(node_uname_info{}, instance)"
    }
   },
   {
    "name": "node3",
    "label": "Host3:",
    "query": {
     "query": "label_values(node_uname_info{}, instance)"
    }
   },
   {
    "name": "node4",
    "label": "Host4:",
    "query": {
     "query": "label_values(node_uname_info{}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Host1: Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"system\"}[$interval])) *100\r\n",
     "legendFormat": "System"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"user\"}[$interval])) *100\r",
     "legendFormat": "User"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"iowait\"}[$interval])) *100\r",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"idle\"}[$interval])) *100\r",
     "legendFormat": "Idle"
    },
    {
     "expr": "(1 - avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"idle\"}[$interval])))*100\r",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Host1: Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node1\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node1\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node1\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node1\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node1\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Host1: Basic network info per interface",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node1\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node1\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Host2: Basic CPU / Mem / Net ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"system\"}[$interval])) *100\r\n",
     "legendFormat": "System"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"user\"}[$interval])) *100\r",
     "legendFormat": "User"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"iowait\"}[$interval])) *100\r",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"idle\"}[$interval])) *100\r",
     "legendFormat": "Idle"
    },
    {
     "expr": "(1 - avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"idle\"}[$interval])))*100\r",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Host1: Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node1\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node1\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node1\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node1\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node1\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Host1: Basic network info per interface",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node1\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node1\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  { "title": "Host3: Basic CPU / Mem / Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"system\"}[$interval])) *100\r\n",
     "legendFormat": "System"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"user\"}[$interval])) *100\r",
     "legendFormat": "User"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"iowait\"}[$interval])) *100\r",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"idle\"}[$interval])) *100\r",
     "legendFormat": "Idle"
    },
    {
     "expr": "(1 - avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"idle\"}[$interval])))*100\r",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Host1: Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node1\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node1\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node1\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node1\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node1\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Host1: Basic network info per interface",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node1\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node1\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Host4: Basic CPU / Mem / Net",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"system\"}[$interval])) *100\r\n",
     "legendFormat": "System"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"user\"}[$interval])) *100\r",
     "legendFormat": "User"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"iowait\"}[$interval])) *100\r",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"idle\"}[$interval])) *100\r",
     "legendFormat": "Idle"
    },
    {
     "expr": "(1 - avg by (instance)(rate(node_cpu_seconds_total{instance=\"$node1\",mode=\"idle\"}[$interval])))*100\r",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Host1: Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node1\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node1\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node1\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node1\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node1\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node1\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node1\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Host1: Basic network info per interface",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node1\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node1\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  }
 ]
}