---

- name: Restart service unit
  service:
    name: unit
    state: restarted

- name: Apply TLS Cert and Key
  ansible.builtin.uri:
    unix_socket: /var/run/control.unit.sock
    url: http://localhost/certificates/bundle
    method: PUT
    body: "{{ lookup('ansible.builtin.file','./files/www.example.com.rsa2k.pem') }}"
    body_format: json

- name: Apply Unit Config
  ansible.builtin.uri:
    unix_socket: /var/run/control.unit.sock
    url: http://localhost/config/
    method: PUT
    body: "{{ lookup('ansible.builtin.file','./files/nunit-config/wordpress.json') }}"
    body_format: json
