---

- name: Create Directory
  file:
    path: "/root/f5j-nginx-performance-lab/docker-compose/locust/result"
    state: directory
    owner: "root"
    group: "root"
    mode: "777"

- name: Start Locust
  shell: |
    docker-compose -f locust/docker-compose-locust.yaml up -d --scale worker=4
  args:
    chdir: ~/f5j-nginx-performance-lab/docker-compose