---
- name: Start Grafana & Prometheus
  shell: |
    docker volume create metrics_data
    docker volume create grafana_data
    docker-compose -f ./docker-compose-grafana-prom.yaml up -d
  args:
    chdir: ~/f5j-nginx-performance-lab/docker-compose/monitor
